version: 0.2.{build}
image: Ubuntu2004
environment:
  sonar_key:
    secure: 9IPGTeBarWlRZdfc1riOp4Vd9eHadSWNzOjUT+su9lrNd3Az6IpT8OvLngqo0t/X
install:
- ps: dotnet tool install --global dotnet-sonarscanner
before_build:
- ps: cd "$($env:APPVEYOR_BUILD_FOLDER)/src"
- ps: nuget restore
- ps: dotnet-sonarscanner begin /k:"MuazOthman_gensam" /d:"sonar.host.url=https://sonarcloud.io" /d:"sonar.login=$($env:sonar_key)" /o:"muazothman" /v:"$($env:APPVEYOR_BUILD_VERSION)" /d:sonar.cs.opencover.reportsPaths="$($env:APPVEYOR_BUILD_FOLDER)/src/**/*.opencover.xml"
build_script:
- ps: cd "$($env:APPVEYOR_BUILD_FOLDER)/src"
- ps: dotnet build
test_script:
- ps: dotnet test --collect "XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
after_test:
- ps: dotnet-sonarscanner end /d:"sonar.login=$($env:sonar_key)"